name: Build bot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        pip install -r requirements.txt
    - name: Compiles bot
      run: |
        python -m py_compile bot.py
    - name: Lint code
      run: |
        python -m pylint bot.py
